### PR TITLE
Added ACE editor support

### PR DESCRIPTION
**Pull request by Zhigalin**

### CODE REVIEW

**Comment by tonsky** [comment]
Well, ACE isn’t a standalone editor, is it? So it should be covered by “Browsers support” section already?

**Comment by Zhigalin** [comment]
Well, a in-browser code editor is a bit more complex than a simple textarea...
Actually I don't know how it could work because every character is placed inside a separate div... But it works.

**Comment by MadcapJake** [comment]
Isn't Atom based on Ace? If so, it actually groups characters by span via a grammar tokenizer.  So if the language grammar groups two chars together, it will come up ligaturized in Fira Code. A cursory inspection of github seems to support this (though each row is actually a `<tr>`).

**Comment by tonsky** [comment]
Ok, I added ACE and CodeMirror to the browsers section

**Pull request closed without merging**
