### PR TITLE
add PHP showcase image to README.md

### PR DESCRIPTION
**Pull request by MrMitch**
This commit adds an image that showcases FiraCode in PHP code.

php

### CODE REVIEW

**Comment by JCMais** [comment]
You probably should add ``$options = [];`` so the ``[]`` can be shown.

**Comment by MrMitch** [comment]
`[]` doesn't render with any special ligature in the latest version of FiraCode.
image

It was removed in 8cecc3c1f23c7f441a05ed337ee2ca616842af47 following the discussion in #92

**Comment by JCMais** [comment]
Oh, my bad. Didn't saw that it was removed.

**Comment by MrMitch** [comment]
@tonsky should I close this ?

**Comment by tonsky** [comment]
Thanks! Great example

**Pull request closed without merging**
