### PR TITLE
added HowToInstall.zip, updated release.sh

### PR DESCRIPTION
**Pull request by TangibleToofa**

### CODE REVIEW

**Comment by tonsky** [comment]
You’re just creating a second archive with the same content FiraCode.zip has

**Comment by TangibleDream** [comment]
Please explain,  this was added in response to https://github.com/tonsky/FiraCode/issues/664

**Comment by TangibleDream** [comment]
Is there something more for me to do?

I create HowToInstall.txt,
Zipped it,
Placed it in the distr folder,
And added a find command in release.sh.

Did I need to do anything else?  Did I do anything incorrectly?

**Comment by tonsky** [comment]
How to install should be a text file that gets added to archive during release.sh. Instead you changed release.sh to generate another archive. Just place a txt file into distr

**Comment by TangibleToofa** [comment]
How does this look?

**Comment by tonsky** [comment]
Cool! Now the file itself needs some formatting. I suggest markdown. Please add headers, lists, code blocks. Also some sections don’t make sense, e.g. mention of the image to compare with. And it needs an URL back to the https://github.com/tonsky/FiraCode somewhere

**Comment by tonsky** [comment]
txt is better I think, cause it’ll open everywhere

**Comment by TangibleToofa** [comment]
Check it out

**Comment by tonsky** [comment]
Thanks! Merged

**Pull request merged**
