### PR TITLE
Erlang compatibility for List Pattern Matching

### PR DESCRIPTION
**Pull request by m-2k**
Exclude ligatures for `[_|_]` `[_,_|_]` `[ _|_ ]` `[ _, _|_ ]` from underscores lookup

Screenshot 2024-10-16 at 18 22 50

### CODE REVIEW

**Comment by m-2k** [comment]
how long will it take to merge?

**Comment by tonsky** [comment]
I don’t think I like inclusion of space in the ignore pattern. You’ll write it either as `[_|_]` or `[ _ | _ ]`, no? With just `[bracket comma] underscore` I can add it

**Comment by m-2k** [comment]
@tonsky 

Screenshot 2024-10-30 at 18 48 48

**Comment by tonsky** [comment]
Thank you!

**Pull request merged**
