### PR TITLE
Add Black Screen to the List of Supported Terminals

### PR DESCRIPTION
**Pull request by shockone**

### CODE REVIEW

**Comment by tonsky** [comment]
thanks!
Nice editor, but I wasn’t able to run it:

```
[~/work/black-screen] npm start

> black-screen@0.0.1 start /Users/prokopov/work/black-screen
> gulp

[22:31:46] Requiring external module babel-core/register
/Users/prokopov/work/black-screen/gulpfile.babel.js:5
const gulp = require("gulp");
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at loader (/Users/prokopov/work/black-screen/node_modules/babel-core/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/prokopov/work/black-screen/node_modules/babel-core/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/Users/prokopov/work/black-screen/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/prokopov/work/black-screen/node_modules/gulp/node_modules/liftoff/index.js:192:16)
```

**Comment by shockone** [comment]
Two questions:
* Is your nodejs version up to date?
* Have you installed dependencies?

**Comment by tonsky** [comment]
```
[~/work/black-screen] node -v
v0.12.7
[~/work/black-screen] npm -v
2.14.1
```
I did
```
npm i
npm start
```
as per instructions

**Comment by shockone** [comment]
The latest version of node is 5.5.0, you know. :)

**Comment by tonsky** [comment]
Got it working, thanks for the help!

**Pull request merged**
