### PR TITLE
Rename HowToInstall.txt to HowToInstall.md

### PR DESCRIPTION
**Pull request by vasilescur**
This change is [Reviewable](https://reviewable.io/reviews/tonsky/firacode/716)

### CODE REVIEW

**Comment by tonsky** [comment]
Why? I’m pretty sure not many people have .md editors installed, whether every OS can open txt somehow

**Comment by Geweldig** [comment]
As the contents of the file is written in markdown I think this should be merged, as the file is currently rendered incorrectly when opened on GitHub. If the main concern to keep the .txt file extension is people being unable to open it because it is not a plaintext file it might be worthwhile to rewrite the file using just plaintext

**Comment by tonsky** [comment]
It may need some cleanup, yes

**Comment by tigermax139** [comment]
What about two variants of `HowToInstall` ?)

**Comment by vasilescur** [comment]
The contents of this file are written in Markdown, so the extension should naturally be `.md`. This is consistent with other files in the repository-- such as `README.md` and `CHANGELOG.md`. While the file could be re-written in plain text, this would lose the clarity and structured format brought by Markdown. 

Furthermore, anyone without a `.md` editor can easily open the file in Notepad or similar, and have exactly the same readability level as the file has right now. This change could only bring improvement.

Finally,. I agree with @vilinski -- _Fira Code_ is, after all, a font for programmers, so I think it's a very fair assumption that the vast majority of those installing it can handle opening a Markdown file. Also, properly naming it as a `.md` file will allow the GitHub website to properly format the file when viewed online.

**Comment by alexpovel** [comment]
I was about to create the exact same pull request when I saw this one.
So, I agree this should be a thing; a Markdown-formatted file should have a suffix of `.md`.
Anyone not familiar can open it in any text editor as a plain-text file. Problem solved!

**Comment by ptkdev** [comment]
We are developers, we know how to open a .md file

**Pull request closed without merging**
