### PR TITLE
Add installation instructions for Visual Studio 2019

### PR DESCRIPTION
**Pull request by xigolle**
Updated the Readme file to include the instructions for Visual Studio 2019.
Also added a wiki page with these instructions (based on the one for Visual Studio 2017).
https://github.com/tonsky/FiraCode/wiki/Visual-Studio-2019-Instructions

### CODE REVIEW

**Comment by tonsky** [comment]
Why do we need separate page for 2019. Maybe better merge and rename them to just “Visual Studio instructions”? Also that wiki page needs screenshots

**Comment by xigolle** [comment]
The splitting of for the 2 seperate pages is for the reason if somewhere in the lifetime of VS2019 the instructions change we can edit just that page and leave 2017 as is. 
Will add some images later this day for 2017 and 2019.

**Comment by tonsky** [comment]
I just merged the pages https://github.com/tonsky/FiraCode/commit/feffa115c5908bc98ca729cf04a1c500332154bb. Please do not create a separate one for each release. Screenshots would be much appreciated. Thanks!

**Comment by xigolle** [comment]
@tonsky Sorry took a little bit longer to add some images. But added them just now to the Wiki.  Just let me know if they are sufficient :-)

**Comment by tonsky** [comment]
Fantastic! Thanks @xigolle

**Pull request closed without merging**
