### PR TITLE
scala/scalaz ligatures

### PR DESCRIPTION
**Pull request by merlinorg**
Adds ligatures for various scala/scalaz/... symbols including type constraints, applicative builder, tagged types, disjunctions, their friends and distant relatives. Disjunction and conjunction (`\/`, `/\`) are treated specially so they only substitute before space, period or leftbracket where they look like types and less like common regexes. Does not include rebuilt font distribution, I'm not that skilled.

### CODE REVIEW

**Comment by merlinorg** [comment]
Touches on issues #292, #191.

**Comment by j-f1** [comment]
Got a screenshot of the ligatures?

**Comment by merlinorg** [comment]
scalaligs

**Comment by dhouck** [comment]
What are those with ligatures disabled? I can guess at some of them, but not all (presumably they’d be clearer if I knew Scala).

**Comment by j-f1** [comment]
My guess:
```
<: >: <% <:< _*
<\/- <\/ -\/ \/ \/- \/> -\/>
\|/ \&/ /\ @@ |@| |+|
-<| <|- -|> |>-
```

**Comment by merlinorg** [comment]
The very circled at is indeed `|@|` which is the applicative builder. The disjunction ligature only kicks in before `.`, `[` or ` `, as...

```
val a = \/.fromTryCatchNonFatal
type T = \/[A, B]
type t = A \/ B
```

These seem not hugely common regex cases.

**Comment by tonsky** [comment]
@merlinorg thanks for taking the effort to make it a pull request. I really like your thinking, but I want Fira Code to stay true to its principles. Those are: ligatures should improve the reading experience, they should not increase confusion and be immediately obvious, they should not break the indentation (e.g. 3-char ligature should take up 3 character spaces without creating too much extra whitespace), and they should work for all languages. I also prefer them to be aestethically pleasing and contribute enough to justify their existence. I also tend not to add very rare combinations as there might be more people hurt by those than there will be people helped by those.

I like the vertical adjustments in `<:` `>:` `<:<` but if we’re doing those I think we should do `:<`, `:>` and `>:>` as well?

I’m not sure about `<%` seems like very minor adjustment.

`_*` feels too much of a stretch

 `\/` and `/\` would cause too much conflicts in escape sequences

`<\/-` `<\/` `\/>` `-\/>` seems too strange. How often are they used? Same about `-\/` `\/-`. Also worried about escape sequences

`\|/` `\&/` would not play nicely as 3-width ligatures

`@@` I like the idea but would prefer to redraw it myself

`|@|` `|+|` are impossible to decypher. I thought that circled `+` stands for `(+)`. They also have width problems—should be 3-char wide, but that would create too much whitespace around it that isn’t even there.

`-<|` `<|-` `-|>` `|>-` are great and would be nice addition to `|>` `<|`

If you don’t mind I will take the ideas from this PR but will add only stuff I see fit & probably redrawn on my own. Thanks for the contribution!

**Comment by doowruc** [comment]
`<%` is used heavily in ASP.Net so if it is implemented then `%>` will also need to be done to match it.

**Comment by dhouck** [comment]
I like `<%` and `%>`. I don’t know how often they’re used so I don’t know if they’d be worth it, though.

**Comment by doowruc** [comment]
In ASP.Net (and classic ASP) they are actually used less and less now I think, mostly on legacy sites.

ASP.Net MVC is (AFAIK) used much more widely now and that uses a different rendering engine (Razor) which use `@` tags for server-side markup.

Some info on `<%` and `%>` is available [here](http://www.tinyint.com/index.php/2011/01/19/asp-net-code-delimiters/)

**Comment by merlinorg** [comment]
... anent `<:` and friends, I just included the main ones from scala/scalaz (although I since added `:<:`) but the missing mirrors would not hurt. If made more opinionated, `<%` and `%>` are defensible although their usage in scala and ASP/JSP are presumably waning. The various friends of `\/` are only useful/used alongside the disjunction ligature itself; with the more restrictive lookup rules I placed on it I find it to not kick in needlessly but ymmv.  All the ligatures suffer from looking out of place in surprising places and so the choice of which to include is obviously personal, I'm happy to close this PR and just use the forked font for my own purposes. Fwiw the ligatures I ended up adding were the following..

```
         ??? ${ _* *_*
     -<<- <~< <~~> >~> ->>-
   <% <:< :<: <: >: :>: >:> %>
  <\/- <\/ -\/ \/ \/- \/> -\/>
     \|/ \&/ /\ @@ |@| |+|
        -<| <|- -|> |>-
```

scalaligs

**Pull request closed without merging**
