### PR TITLE
Improve build script & fonts in distr

### PR DESCRIPTION
**Pull request by thundernixon**
Previously, I had several metadata-fixing tools in the `move-check.sh` script, to fix fonts for Google Fotns. However, these are generally useful for fonts that people might self-host, as well, so I've moved these steps into the build script.

I also made the CSS a bit more resilient.

### CODE REVIEW

**Comment by tonsky** [comment]
Thanks!!

**Review by itsMo07 — COMMENTED** [review]
Fg

**Comment by RubenVerg** [comment]
why are you just posting random two letters around?

- RubenVerg ❤️


________________________________

**Comment by itsMo07** [comment]
Wh

**Pull request merged**
