### PR TITLE
readme: add support instructions for emacs

### PR DESCRIPTION
**Pull request by seanfarley**
Based off an email request to Yamamoto Mitsuharu, he was able to help get this to work because he is such a badass with lisp.

### CODE REVIEW

**Comment by seanfarley** [comment]
This is a lot of code to put in the README so I understand if you want it to be put into a wiki or something.

**Comment by tonsky** [comment]
Thanks! Put it there https://github.com/tonsky/FiraCode/wiki/Setting-up-Emacs

**Comment by seanfarley** [comment]
Awesome, thanks!

**Comment by afincato** [comment]
Sorry to bring this up two years after, but the wiki page is empty, what happened to it? 

Would like to use this set of instructions for emacs somehow. Thanks!

**Pull request closed without merging**
