### PR TITLE
Sublime Text 3 now has font ligature support

### PR DESCRIPTION
**Pull request by alfredbez**
see also https://forum.sublimetext.com/t/dev-build-3145/32340 or https://news.ycombinator.com/item?id=15413543

### CODE REVIEW

**Comment by mrolla** [comment]
I think it's worth mentioning that for now it's only in dev builds, which a lot of people don't know the existence of.

**Comment by thevasya** [comment]
Right, it would be nice to mention that it only works with dev builds from 3146 and up.

**Comment by alfredbez** [comment]
Thanks, I added a commit which mentions that

**Comment by tonsky** [comment]
Let’s wait till the proper support. So far lots of bugs and only Windows is supported, is that right?

**Comment by alfredbez** [comment]
> [...] only Windows is supported [...]

No, I'm using this on Ubuntu:
image

**Comment by asfktz** [comment]
Works on mac too

image

**Comment by thevasya** [comment]
Yeah, I'm also using Ubuntu, and it seems to be working, at least with JavaScript files. There are people who report issues though, and the current implementation probably has a lot of small bugs.

Quick example. Here is an example with built-in `Erlang` syntax.

image

And here is the same code with built-in `Erlang (HTML)` syntax.

image

The first example _tries_ to draw a ligature, but it can't connect more than two equality signs for whatever reason.

**Comment by tonsky** [comment]
@thevasya yeah, other editors went through this too. It’s because syntax highlighter actually breaks sequences sometimes 

@asfktz @alfredbez thx for confirming, my mistake

Merging now.

FINALLY! YAY!

**Pull request merged**
